Error if config file is not found

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -61,8 +61,11 @@ puts-step "Running pelican"
 
 if [[ -f publishconf.py ]]; then
   CONFIG_FILE="publishconf.py"
-else
+elif [[ -f pelicanconf.py ]]; then
   CONFIG_FILE="pelicanconf.py"
+else
+  puts-warn "A pelicanconf.py or publishconf.py file is required."
+  exit 1
 fi
 
 pelican -d -o $BUILD_DIR/public -s $CONFIG_FILE $BUILD_DIR/content | indent
